package edu.uiuc.cs427app;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a City entity in the database.
 * Each city entry is associated with a user  
 * and includes an id (as primary key, auto-generated by Room), 
 * the name of the city, and the user's ID.
 */
@Entity
public class City {
    @PrimaryKey(autoGenerate=true)
    public int id;
    public String cityName;
    public String userID;

    /**
     * Constructs a new City entity with the city name and user ID.
     * 
     * @param cityName the name of the city
     * @param userID the ID of the user who added the city to their list
     */
    public City(String cityName, String userID) {
        this.cityName = cityName;
        this.userID = userID;
    }
}